name = "Landing Page"
license = "Apache2"
licenselink = "https://github.com/enaml-ops/landingpage/blob/master/LICENSE.md"
description = "enaml landing page theme."
homepage = "https://github.com/enaml-ops/landingpage"
tags = ["oss", "landing page"]
features = ["social", "images" ]
min_version= 0.14

[author]
     name = "jcalabrese"

[original]
    author =  "crakjie"
    homepage = "https://github.com/crakjie/landing-page-hugo"
    repo = "https://github.com/crakjie/landing-page-hugo"
