baseurl = "http://enaml.pezapp.io/"
languageCode = "en-us"
title = "Enaml"
theme = "cf"

[params]
  image = "<img src=\"/img/enaml_white_green_slogan-honeycomb.pmg\"></img>"

[[params.actionlink]]
    title = "download"
    icon = "cloud-download"
    url = "/downloads/release"

[[params.social]]
    title = "github"
    icon = "github"
    url = "https://github.com/enaml-ops"

[[params.social]]
    title = "gitter"
    icon = "comment"
    url = "https://gitter.im/enaml-ops"
